name: VPM Repo Update

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # 信頼性NO.1のVPMリポジトリ生成アクション
      # ファイル名などを直接指定しなくて良いのでエラーが起きにくいです
      - name: VPM Repo Update
        uses: vranas/vpm-repo-action@v0.1.4
        with:
          # パッケージが入っているフォルダを指定
          packages_directory: Packages
          # 生成されるカタログのベースURL（あなたのPagesのURL）
          repository_url: https://qubeleyddj.github.io/vpm-repos/

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: .

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4