name: VPM Repo Update

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # vrc-getコマンドをインストール
      - name: Install vrc-get
        run: |
          curl -L https://github.com/vrc-get/vrc-get/releases/latest/download/vrc-get-ubuntu-x86_64 -o vrc-get
          chmod +x vrc-get

      # index.jsonを生成/更新
      - name: Update VPM Repo
        run: |
          ./vrc-get vpm repo make . --package Packages

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: .

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
